### ISSUE TITLE
Saving project does not save distributed loads

### ISSUE THREAD

**Issue by kmccullen97** [kmccullen97/statics-solver#4]

**Comment by GRsni** [comment]
I'm on it.

**Comment by kmccullen97** [comment]
Okay.  I created all the classes I think we need in the ```determinate-solution``` branch.  What should the next step be.

1. We could work on using these classes to solve beam
2. We could rewrite the load and save algorithms to load the new classes.

**Comment by GRsni** [comment]
I usually start with the loading and saving aspect of my projects. Makes loading and testing files much easier.

**Comment by kmccullen97** [comment]
Okay. I am working on loading the files.  Would you like to work on saving?

**Comment by GRsni** [comment]
Sure.

**Comment by kmccullen97** [comment]
I just pushed some changes to the ```determinate-solution``` branch so if you want to update to the newest changes.

**Comment by GRsni** [comment]
Got the new parser working. Saves and loads distributed loads into the files. Found some rounding errors will testing it though.

**Comment by GRsni** [comment]
This issue can be closed now.
