### ISSUE TITLE
Beam class refactoring.

### ISSUE THREAD

**Issue by GRsni** [kmccullen97/statics-solver#6]
In light of the recent changes to the majority of the classes, and given that every other class has its own  and y position, it only makes sense that the Beam class has those too. That way, we will be able to create more complex structures down the line.

**Comment by kmccullen97** [comment]
Good Idea! Yeah, down the line I was thinking the program would extend to solving trusses which require several beams.

**Comment by GRsni** [comment]
Cool. Are you taking over this issue then?

**Comment by kmccullen97** [comment]
I don't have a preference, what are some of the properties the beam class should have?  Also I was able to get some time to work on the project today.  Right now I am fixing the GUI to match the new classes.  I should be done soon.

**Comment by GRsni** [comment]
I'm thinking start x,y, end x,y. From those we can extrapolate the length. Don't know if we need anything else as of right now.

**Comment by kmccullen97** [comment]
Some things have to be done in order.  I will add my code im finishing up now, want to create a pull request with the save algorithm? (if you finished it) and then we can make some changes to the beam class.

**Comment by kmccullen97** [comment]
Okay I pushed my most recent changes.

**Comment by kmccullen97** [comment]
Maybe for coordinates we could do something like this . . .
```
struct Coordinates {
      double x;
      double y;
};
```
and then the class can have properties
```
Coordinates begining;
Coordinates ending;
```

**Comment by GRsni** [comment]
That should do the job. And it'll make things easier when implementing the beam visualization.

**Comment by GRsni** [comment]
I believe there's an error in the `Parser::buildRollerSupportClass` function. Since the value `isDirY` is a boolean, the parser shouldn't try to cast it into a double, should it?

**Comment by kmccullen97** [comment]
Good catch!  Also for some reason i check for the condition of “x” twice.  Those both need to be fixed.

**Comment by GRsni** [comment]
Just finished the `Parser::write` function. I separated each class into its own `std::string` function, that get appended to the file. Also corrected those two errors in the `buildRollerSupportClass` function.

**Comment by kmccullen97** [comment]
Thanks!  Ill take a look at it now.

**Comment by kmccullen97** [comment]
I merged your pull request and merged the branch into master.
